version: 2.1

parameters:
  test:
    type: string
    default: "I'm a test"

jobs:
  configyml:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "i'm config.yml" # run the `echo` command
      - run: echo << pipeline.parameters.test >> # print the value of the test parameter

workflows:
  configYML:
    jobs:
      - configyml
